skip_tests = [
    # TestNN under test_nn.py
    "test_RNN_dropout_state",
    "test_rnn_check_device",
    # TestTorch under test_torch.py
    "test_index_add_correctness",
    "test_print",
    # TestCuda under test_cuda.py
    "test_hip_device_count",
    "test_host_memory_stats",
    "test_nvtx",
    "test_device_count_not_cached_pre_init",
    # TestCuda under test_cuda.py, failing on gfx942 (#1143)
    "test_float32_matmul_precision_get_set ",
    # TestCude under test_cuda.py, failing on gfx942 (#1151)
    "test_graph_concurrent_replay",
    # TestCuda under test_cuda.py, failing on gfx950
    "test_preferred_blas_library_settings",
    # TestCudaAutocast under test_cuda.py, failing on gfx950
    "test_autocast_torch_bf16",
    "test_autocast_torch_fp16",
    # TestMemPool under test_cuda.py
    "test_mempool_with_allocator",
    # TestBinaryUfuncsCUDA under test_binary_ufuncs
    "test_cuda_tensor_pow_scalar_tensor_cuda",
    # TestUnaryUfuncsCUDA under test_unary_ufuncs.py
    "test_reference_numerics_extremal__refs_special_spherical_bessel_j0_cuda_float32",
    "test_reference_numerics_extremal__refs_special_spherical_bessel_j0_cuda_float64",
    "test_reference_numerics_extremal_special_airy_ai_cuda_float32",
    "test_reference_numerics_extremal_special_airy_ai_cuda_float64",
    "test_reference_numerics_extremal_special_spherical_bessel_j0_cuda_float32",
    "test_reference_numerics_extremal_special_spherical_bessel_j0_cuda_float64",
    "test_reference_numerics_large__refs_nn_functional_mish_cuda_float16",
    "test_reference_numerics_large__refs_special_spherical_bessel_j0_cuda_float32",
    "test_reference_numerics_large__refs_special_spherical_bessel_j0_cuda_float64",
    "test_reference_numerics_large__refs_special_spherical_bessel_j0_cuda_int16",
    "test_reference_numerics_large__refs_special_spherical_bessel_j0_cuda_int32",
    "test_reference_numerics_large__refs_special_spherical_bessel_j0_cuda_int64",
    "test_reference_numerics_large_nn_functional_mish_cuda_float16",
    "test_reference_numerics_large_special_spherical_bessel_j0_cuda_float32",
    "test_reference_numerics_large_special_spherical_bessel_j0_cuda_float64",
    "test_reference_numerics_large_special_spherical_bessel_j0_cuda_int16",
    "test_reference_numerics_large_special_spherical_bessel_j0_cuda_int32",
    "test_reference_numerics_large_special_spherical_bessel_j0_cuda_int64",
    "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_bool",
    "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_float32",
    "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_float64",
    "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_int16",
    "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_int32",
    "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_int64",
    "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_int8",
    "test_reference_numerics_normal__refs_special_spherical_bessel_j0_cuda_uint8",
    "test_reference_numerics_normal_special_airy_ai_cuda_bool",
    "test_reference_numerics_normal_special_airy_ai_cuda_float32",
    "test_reference_numerics_normal_special_airy_ai_cuda_float64",
    "test_reference_numerics_normal_special_airy_ai_cuda_int16",
    "test_reference_numerics_normal_special_airy_ai_cuda_int32",
    "test_reference_numerics_normal_special_airy_ai_cuda_int64",
    "test_reference_numerics_normal_special_airy_ai_cuda_int8",
    "test_reference_numerics_normal_special_airy_ai_cuda_uint8",
    "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_bool",
    "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_float32",
    "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_float64",
    "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_int16",
    "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_int32",
    "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_int64",
    "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_int8",
    "test_reference_numerics_normal_special_spherical_bessel_j0_cuda_uint8",
    "test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_float32",
    "test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_float64",
    "test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_int16",
    "test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_int32",
    "test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_int64",
    "test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_int8",
    "test_reference_numerics_small__refs_special_spherical_bessel_j0_cuda_uint8",
    "test_reference_numerics_small_special_airy_ai_cuda_float32",
    "test_reference_numerics_small_special_airy_ai_cuda_float64",
    "test_reference_numerics_small_special_airy_ai_cuda_int16",
    "test_reference_numerics_small_special_airy_ai_cuda_int32",
    "test_reference_numerics_small_special_airy_ai_cuda_int64",
    "test_reference_numerics_small_special_airy_ai_cuda_int8",
    "test_reference_numerics_small_special_airy_ai_cuda_uint8",
    "test_reference_numerics_small_special_spherical_bessel_j0_cuda_float32",
    "test_reference_numerics_small_special_spherical_bessel_j0_cuda_float64",
    "test_reference_numerics_small_special_spherical_bessel_j0_cuda_int16",
    "test_reference_numerics_small_special_spherical_bessel_j0_cuda_int32",
    "test_reference_numerics_small_special_spherical_bessel_j0_cuda_int64",
    "test_reference_numerics_small_special_spherical_bessel_j0_cuda_int8",
    "test_reference_numerics_small_special_spherical_bessel_j0_cuda_uint8",
    # Explicitly deselected since givind segfault
    "test_unused_output_device_cuda",
    "test_pinned_memory_empty_cache",
]
# Emit the -k expression
expr = "not " + " and not ".join(skip_tests)
print(expr)
