name: Release portable Linux PyTorch Wheels

on:
  workflow_call:
    inputs:
      amdgpu_family:
        required: true
        type: string
      release_type:
        description: The type of release to build ("nightly", or "dev")
        type: string
        default: "dev"
      s3_subdir:
        description: S3 subdirectory, not including the GPU-family
        type: string
        default: "v2"
      cloudfront_url:
        description: CloudFront URL pointing to Python index
        type: string
        default: "https://d25kgig7rdsyks.cloudfront.net/v2"
      rocm_version:
        description: ROCm version to pip install
        type: string
  workflow_dispatch:
    inputs:
      amdgpu_family:
        required: true
        type: string
      release_type:
        description: The type of release to build ("nightly", or "dev")
        type: string
        default: "dev"
      s3_subdir:
        description: S3 subdirectory, not including the GPU-family
        type: string
        default: "v2"
      cloudfront_url:
        description: CloudFront URL pointing to Python index
        type: string
        default: "https://d25kgig7rdsyks.cloudfront.net/v2"
      rocm_version:
        description: ROCm version to pip install
        type: string


permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: PyTorch Wheels | ${{ inputs.amdgpu_family }} | Python ${{ matrix.python_version }}
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.11", "3.12", 3.13]
        pytorch_version: ["release/2.7"]
        include:
          - pytorch_version: release/2.7
            pytorch_patchset: "rocm_2.7"

    uses: ./.github/workflows/build_portable_linux_pytorch_wheels.yml
    with:
      amdgpu_family: ${{ inputs.amdgpu_family }}
      python_version: ${{ matrix.python_version }}
      release_type: ${{ inputs.release_type }}
      s3_subdir: ${{ inputs.s3_subdir }}
      cloudfront_url: ${{ inputs.cloudfront_url }}
      rocm_version: ${{ inputs.rocm_version }}
      pytorch_version: ${{ matrix.pytorch_version }}
      pytorch_patchset: ${{ matrix.pytorch_patchset }}
