name: Setup

on:
  workflow_call:
    outputs:
      enable_build_jobs:
        description: Whether to enable build jobs.
        value: ${{ jobs.setup.outputs.enable_build_jobs }}
      linux_amdgpu_families:
        description: Linux families to run builds and tests on.
        value: ${{ jobs.setup.outputs.linux_amdgpu_families }}
      windows_amdgpu_families:
        description: Windows families to run builds and tests for.
        value: ${{ jobs.setup.outputs.windows_amdgpu_families }}

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-24.04
    env:
      # The commit being checked out is the merge commit for a PR. Its first
      # parent will be the tip of the base branch.
      BASE_REF: HEAD^
    outputs:
      enable_build_jobs: ${{ steps.configure.outputs.enable_build_jobs }}
      linux_amdgpu_families: ${{ steps.configure.outputs.linux_amdgpu_families }}
      windows_amdgpu_families: ${{ steps.configure.outputs.windows_amdgpu_families }}
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # We need the parent commit to do a diff
          fetch-depth: 2

      - name: Set PR_LABELS variable with labels assigned to pull request
        if: ${{ github.event.pull_request }} # only set PR labels var if this is a pull request
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo "PR_LABELS=$(gh pr view ${PR_NUMBER} --json labels)" >> $GITHUB_ENV

      - name: "Configuring CI options"
        id: configure
        env:
          INPUT_LINUX_AMDGPU_FAMILIES: ${{ github.event.inputs.linux_amdgpu_families }}
          LINUX_USE_PREBUILT_ARTIFACTS: ${{ github.event.inputs.linux_use_prebuilt_artifacts }}
          INPUT_WINDOWS_AMDGPU_FAMILIES: ${{ github.event.inputs.windows_amdgpu_families }}
          WINDOWS_USE_PREBUILT_ARTIFACTS: ${{ github.event.inputs.windows_use_prebuilt_artifacts }}
        run: ./build_tools/github_actions/configure_ci.py
