name: Setup

on:
  workflow_call:
    outputs:
      enable_build_jobs:
        description: Whether to enable build jobs.
        value: ${{ jobs.setup.outputs.enable_build_jobs }}
      build_linux_amdgpu_families:
        description: Linux families to run builds on.
        value: ${{ jobs.setup.outputs.build_linux_amdgpu_families }}
      build_windows_amdgpu_families:
        description: Windows families to run builds for.
        value: ${{ jobs.setup.outputs.build_windows_amdgpu_families }}
      test_linux_amdgpu_families:
        description: Linux families to run tests for.
        value: ${{ jobs.setup.outputs.test_linux_amdgpu_families }}
      test_windows_amdgpu_families:
        description: Windows families to run tests for.
        value: ${{ jobs.setup.outputs.test_windows_amdgpu_families }}

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-24.04
    env:
      # The commit being checked out is the merge commit for a PR. Its first
      # parent will be the tip of the base branch.
      BASE_REF: HEAD^
    outputs:
      enable_build_jobs: ${{ steps.configure.outputs.enable_build_jobs }}
      build_linux_amdgpu_families: ${{ steps.configure.outputs.build_linux_amdgpu_families }}
      build_windows_amdgpu_families: ${{ steps.configure.outputs.build_windows_amdgpu_families }}
      test_linux_amdgpu_families: ${{ steps.configure.outputs.test_linux_amdgpu_families }}
      test_windows_amdgpu_families: ${{ steps.configure.outputs.test_windows_amdgpu_families }}
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # We need the parent commit to do a diff
          fetch-depth: 2

      - name: Set PR_LABELS variable with labels assigned to pull request
        if: ${{ github.event.pull_request }} # only set PR labels var if this is a pull request
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo "PR_LABELS=$(gh pr view ${PR_NUMBER} --json labels)" >> $GITHUB_ENV

      - name: "Configuring CI options"
        id: configure
        env:
          INPUT_BUILD_LINUX_AMDGPU_FAMILIES: ${{ github.event.inputs.build_linux_amdgpu_families }}
          INPUT_BUILD_WINDOWS_AMDGPU_FAMILIES: ${{ github.event.inputs.build_windows_amdgpu_families }}
          INPUT_TEST_LINUX_AMDGPU_FAMILIES: ${{ github.event.inputs.test_linux_amdgpu_families }}
          INPUT_TEST_WINDOWS_AMDGPU_FAMILIES: ${{ github.event.inputs.test_windows_amdgpu_families }}
        run: ./build_tools/github_action/configure_ci.py
